sudo: required
group: deprecated-2017Q3
language: scala
scala:
- 2.11.8
services:
- docker
before_install:
- "./tools/travis/setup.sh"
install: true
script:
- "./tools/travis/build.sh && ./tools/travis/deploy.sh && ./tools/travis/test.sh"
deploy:
- provider: script
  script: "./tools/travis/publish.sh csantanapr ${TRAVIS_TAG%@*} ${TRAVIS_TAG##*@}"
  on:
    tags: true
    all_branches: true
env:
  global:
  - secure: ekeKM0bPtGx051FdMOUmqK8yDGQGlyGkJeMU+PAzwWf2XBGzl3SQijOse6uRpyMT/ik3V4rO3CsW+Bdlsu50ylF8nKGVtTpuISTetUCtDHg6m8Fwro//JeXHi3ufJaHtNNos5m8ZmX8rkGZLLSsIwrNQzYHHfiqDhdAL642snLfk3qddjjRBdYD7jGQBr6EwVu5sEORmDJf63I4wwW8fI7olBtIa4W1xW/2dZGoxNU984ypOzG0yoerxgxsuD1ZchS9R93NEG8kcQLpmzqYMFN9XguqXWdp4f8ImbSIGQ0ANDtHIGs+7ZX56fuDA0VsDwK9OCIfG1ZrsO94/fdb/sbSKKuYc0u4l5SVx+n6gdttikGJT6IMM2kRQ5eT/SbJiZshyLkB117IVq3JHTIS3alDSIchFP589sVxfAVzZJ89p5cq7g2JU+weObgxd6Tp/rkEjF5Obo2/5iFf+J5Lf56Ei83SnmYeu7maAzIv+fLzTONymWpCwOtQcif4LeiMNTUdgYtHRBKRCFaMEuOaGi20YuIyoy+OULM/KUFDHwIJROkNFZ+SQ19Jx0qQOIY85E8+D4JBLcXp8VZVGMY+ZnoE76ih/WZZ8wl3zwq0+l53sYhOWUfo5fFSxqg5Ac6gG9OTeO4PmmV/m7ZKdFWFbGbB4qhBq+4swsVpOR+cMuUQ=
  - secure: dMiAsOrklxVR/tkyM11pibEpqdz1qEjziDU1slIYCG4PFRmX9DC9s+fe5gnOCLhyXmt0khz+MG5Pg9bjOma06XbaUAxPvQ+pAf1/OO/e96VLLEo7Bz4jY8qJlvQTfDbAJFlmXOThNu81uNWAvccb+7+Bf/26UOH5vmAvpdIGTsudU1kmC4C+WYRNjtY0us1OPP6jabKZ7jCnQ8m5rAaUPAwuyiwKPEM+Uk0Yo0SvyiMyxihJIJnPi3kT7D0wqQdq9l9WGWSJRCnu6sRpc/VFDRfIcAnxVrg/AuGRxXedO8QdJvJTugxmIxbwB3bYGHZBfHIQkiQfo+7urWXpApNr5ytUjMm0u6ktb53zjhGm2T16Ow04DByT8FWyMnak+ekyV2v7E037Gdq28SgclbZTTJYMtix0rylt/d70upsDbiOKulxWhhIIv1+qZa9kaclW/FXe+0VziSSspJv6ZzXe1DBEpi/W3dm6/GUzbm41h/5agnvCspJ7itsksaXOwCDB3jSCMcqpW9JiLjDyVklycF9QsGUPOa9hOA3eTve2Y3G3ToPFG7tCZYj/SbN6Cm6jpuFcczjT/Lps8XNg0jDcpfZJYP+vWiPa/4vJdo/NAvOdr+VesxAC/2BIGu4OSBi/ayXeEDa8QEen7BCmfYWAtkTsKhO6JNx81e1KekT802o=
